"""Own disassembly front end (disasm/): fire tests, decline tests, SBK1 grade.

Every rule gets a test that it FIRES on its motivating shape, because each of
the rules here declined silently at least once while being written: the
static-function grader read zero sources (path suffix), and the padding
boundary rule never matched (`str(reg)` is "<RegGprO32: sp (29)>").
"""

import os

import pytest

from disasm import code_extent, functions, rom
from disasm.rom import Segment

VRAM = 0x80000000
JR_RA, NOP = 0x03E00008, 0x00000000
JAL = 0x0C000040                   # jal 0x80000100
MOVE_A0_ZERO = 0x00002025
PROLOGUE = 0x27BDFFE8              # addiu sp, sp, -0x18
LW_T6 = 0x8C8E0000                 # lw t6, 0(a0)
ADDU_V0 = 0x01CE1021               # addu v0, t6, t6
ADDIU_V0 = 0x24420001              # addiu v0, v0, 1


def dec_of(words):
    data = b"".join(w.to_bytes(4, "big") for w in words)
    seg = Segment("t", 0, len(data), VRAM)
    return code_extent.Decoder(data, seg)


# ------------------------------------------------------------------ stage 1

def test_normalize_all_three_byte_orders():
    z64 = bytes([0x80, 0x37, 0x12, 0x40, 1, 2, 3, 4])
    v64 = bytes([0x37, 0x80, 0x40, 0x12, 2, 1, 4, 3])
    n64 = bytes([0x40, 0x12, 0x37, 0x80, 4, 3, 2, 1])
    for raw, order in ((z64, "z64"), (v64, "v64"), (n64, "n64")):
        assert rom.normalize(raw) == (z64, order)
    with pytest.raises(ValueError):
        rom.normalize(b"\0\0\0\0")


# ------------------------------------------------------------------ padding

def test_split_padding_keeps_delay_slot_nop_and_cuts_alignment():
    dec = dec_of([ADDIU_V0, JR_RA, NOP, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 20) == (12, 8)


def test_split_padding_after_noreturn_jal():
    # __osCleanupThread: jal osDestroyThread; move a0,zero; then two pad words.
    dec = dec_of([JAL, MOVE_A0_ZERO, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 16) == (8, 8)


def test_split_padding_declines_after_ordinary_code():
    # A load-delay nop after ordinary code is not known padding.
    dec = dec_of([LW_T6, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 12) == (12, 0)


def test_padding_boundary_fires_on_osPfsIsPlug_shape():
    words = [JAL, MOVE_A0_ZERO, NOP, NOP, PROLOGUE, JR_RA, NOP, NOP]
    dec = dec_of(words)
    assert functions.padding_boundaries(dec, VRAM, VRAM + 32) == {VRAM + 16}


def test_padding_boundary_needs_a_prologue():
    # Same zeros, but a leaf body after them: no split (left to spimdisasm).
    words = [JAL, MOVE_A0_ZERO, NOP, NOP, ADDIU_V0, JR_RA, NOP, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == set()


def test_padding_boundary_ignores_load_delay_nops():
    # lw; nop; nop then a prologue-shaped word on a 16-byte boundary: the zeros
    # follow ordinary code, not a control transfer, so they are not padding.
    words = [ADDIU_V0, LW_T6, NOP, NOP, PROLOGUE, JR_RA, NOP, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == set()


# ------------------------------------------------------------------ stage 2

def test_walk_ends_at_return_past_forward_branch():
    BNEZ_FWD = 0x14800003          # bnez a0, +3 (to index 4)
    words = [BNEZ_FWD, NOP, JR_RA, NOP, ADDU_V0, JR_RA, NOP]
    w = dec_of(words).walk(VRAM)
    assert w.end == VRAM + 28


def test_walk_refuses_invalid_instruction():
    w = dec_of([ADDIU_V0, 0x00000005, JR_RA, NOP]).walk(VRAM)
    assert w.end is None


# ------------------------------------------------------------------ SBK1

SBK1 = os.path.expanduser("~/decomp/sbk1")
ROM = os.path.join(SBK1, "snowboardkids.z64")


@pytest.fixture(scope="module")
def sbk1():
    if not os.path.exists(ROM):
        pytest.skip("SBK1 ROM not present")
    from disasm import run
    fe = run.front_end(ROM)
    return fe, run.receipt(fe, SBK1)


@pytest.mark.grounded
def test_sbk1_boot_segment_from_entry_code(sbk1):
    seg = sbk1[0]["segment"]
    # The reference yaml's entry+main: 0x1000..0xE35C0 at 0x80000400.
    assert (seg.rom_start, seg.rom_end, seg.vram) == (0x1000, 0xE35C0, 0x80000400)


@pytest.mark.grounded
def test_sbk1_code_extent_brackets_rsp_microcode(sbk1):
    ext = sbk1[0]["extent"]
    assert ext.rom(ext.text_end) == 0xB19D0          # CPU .text ends
    assert ext.rom(ext.data_start) == 0xB3CF0        # first CPU data access
    # rspboot, aspMain, f3dlx: address-taken, never executed by the CPU.
    assert [ext.rom(v) for v in ext.non_cpu_entries] == [0xB19D0, 0xB1AA0, 0xB28C0]


@pytest.mark.grounded
def test_sbk1_seed_trust_keeps_jal_targets(sbk1):
    # A seed registered without isAutogenerated deleted this function.
    starts = {f.vram for f in sbk1[0]["functions"]}
    assert 0x80000450 in starts                        # initControllerSubsystem
    assert 0x800A64E0 in starts                        # __osException (pointer only)


@pytest.mark.grounded
def test_sbk1_padding_boundary_fires(sbk1):
    fe = sbk1[0]
    dec = code_extent.Decoder(fe["data"], fe["segment"])
    found = functions.padding_boundaries(dec, fe["segment"].vram, fe["extent"].text_end)
    assert 0x800A6DE0 in found                         # osPfsIsPlug
    starts = {f.vram: f for f in fe["functions"]}
    assert starts[0x800A6DD0].size == 8                # __osCleanupThread


@pytest.mark.grounded
def test_sbk1_grade_every_disagreement_explained(sbk1):
    g = sbk1[1]["grade"]
    s = g["functions"]
    for bucket in ("size_padding", "size_other", "missed_start", "extra_start",
                   "stale_whitelist"):
        assert s[bucket] == 0, (bucket, g["disagreements"].get(bucket))
    assert s["whitelisted"] == 2
    assert s["exact"] >= 2116                          # ratchet
    # Grader fires: statics recovered, reverse-order objects measured.
    assert s["start_only_uncheckable_size"] + s["uncheckable_static_start"] == 12
    assert g["reference_object_order"].get("reverse", 0) >= 1
    assert g["reference_unexplained_intervals"] == []
