"""Own disassembly front end (disasm/): fire tests, decline tests, SBK1 grade.

Every rule gets a test that it FIRES on its motivating shape, because each of
the rules here declined silently at least once while being written: the
static-function grader read zero sources (path suffix), and the padding
boundary rule never matched (`str(reg)` is "<RegGprO32: sp (29)>").
"""

import os

import pytest

from disasm import code_extent, functions, rom
from disasm.rom import Segment

VRAM = 0x80000000
JR_RA, NOP = 0x03E00008, 0x00000000
JAL = 0x0C000040                   # jal 0x80000100
MOVE_A0_ZERO = 0x00002025
PROLOGUE = 0x27BDFFE8              # addiu sp, sp, -0x18
LW_T6 = 0x8C8E0000                 # lw t6, 0(a0)
ADDU_V0 = 0x01CE1021               # addu v0, t6, t6
ADDIU_V0 = 0x24420001              # addiu v0, v0, 1


def dec_of(words):
    data = b"".join(w.to_bytes(4, "big") for w in words)
    seg = Segment("t", 0, len(data), VRAM)
    return code_extent.Decoder(data, seg)


# ------------------------------------------------------------------ stage 1

def test_normalize_all_three_byte_orders():
    z64 = bytes([0x80, 0x37, 0x12, 0x40, 1, 2, 3, 4])
    v64 = bytes([0x37, 0x80, 0x40, 0x12, 2, 1, 4, 3])
    n64 = bytes([0x40, 0x12, 0x37, 0x80, 4, 3, 2, 1])
    for raw, order in ((z64, "z64"), (v64, "v64"), (n64, "n64")):
        assert rom.normalize(raw) == (z64, order)
    with pytest.raises(ValueError):
        rom.normalize(b"\0\0\0\0")


# ------------------------------------------------------------------ padding

def test_split_padding_keeps_delay_slot_nop_and_cuts_alignment():
    dec = dec_of([ADDIU_V0, JR_RA, NOP, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 20) == (12, 8)


def test_split_padding_after_noreturn_jal():
    # __osCleanupThread: jal osDestroyThread; move a0,zero; then two pad words.
    dec = dec_of([JAL, MOVE_A0_ZERO, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 16) == (8, 8)


def test_split_padding_declines_after_ordinary_code():
    # A load-delay nop after ordinary code is not known padding.
    dec = dec_of([LW_T6, NOP, NOP])
    assert functions.split_padding(dec, VRAM, 12) == (12, 0)


def test_padding_boundary_fires_on_osPfsIsPlug_shape():
    words = [JAL, MOVE_A0_ZERO, NOP, NOP, PROLOGUE, JR_RA, NOP, NOP]
    dec = dec_of(words)
    assert functions.padding_boundaries(dec, VRAM, VRAM + 32) == {VRAM + 16}


def test_padding_boundary_ignores_load_delay_nops():
    # lw; nop; nop then a prologue-shaped word on a 16-byte boundary: the zeros
    # follow ordinary code, not a control transfer, so they are not padding.
    words = [ADDIU_V0, LW_T6, NOP, NOP, PROLOGUE, JR_RA, NOP, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == set()


# ------------------------------------------------------------------ stage 2

def test_walk_ends_at_return_past_forward_branch():
    BNEZ_FWD = 0x14800003          # bnez a0, +3 (to index 4)
    words = [BNEZ_FWD, NOP, JR_RA, NOP, ADDU_V0, JR_RA, NOP]
    w = dec_of(words).walk(VRAM)
    assert w.end == VRAM + 28


def test_walk_refuses_invalid_instruction():
    w = dec_of([ADDIU_V0, 0x00000005, JR_RA, NOP]).walk(VRAM)
    assert w.end is None


# ------------------------------------------------------------------ SBK1

SBK1 = os.path.expanduser("~/decomp/sbk1")
ROM = os.path.join(SBK1, "snowboardkids.z64")


@pytest.fixture(scope="module")
def sbk1():
    if not os.path.exists(ROM):
        pytest.skip("SBK1 ROM not present")
    from disasm import run
    fe = run.front_end(ROM)
    return fe, run.receipt(fe, SBK1)


@pytest.mark.grounded
def test_sbk1_boot_segment_from_entry_code(sbk1):
    seg = sbk1[0]["segment"]
    # The reference yaml's entry+main: 0x1000..0xE35C0 at 0x80000400.
    assert (seg.rom_start, seg.rom_end, seg.vram) == (0x1000, 0xE35C0, 0x80000400)


@pytest.mark.grounded
def test_sbk1_code_extent_brackets_rsp_microcode(sbk1):
    ext = sbk1[0]["extent"]
    assert ext.rom(ext.text_end) == 0xB19D0          # CPU .text ends
    assert ext.rom(ext.data_bound) == 0xB3CF0        # first CPU data access
    # rspboot, aspMain, f3dlx: address-taken, never executed by the CPU.
    assert [ext.rom(v) for v in ext.non_cpu_entries] == [0xB19D0, 0xB1AA0, 0xB28C0]


@pytest.mark.grounded
def test_sbk1_seed_trust_keeps_jal_targets(sbk1):
    # A seed registered without isAutogenerated deleted this function.
    starts = {f.vram for f in sbk1[0]["functions"]}
    assert 0x80000450 in starts                        # initControllerSubsystem
    assert 0x800A64E0 in starts                        # __osException (pointer only)


@pytest.mark.grounded
def test_sbk1_padding_boundary_fires(sbk1):
    fe = sbk1[0]
    dec = code_extent.Decoder(fe["data"], fe["segment"])
    found = functions.padding_boundaries(dec, fe["segment"].vram, fe["extent"].text_end)
    assert 0x800A6DE0 in found                         # osPfsIsPlug
    starts = {f.vram: f for f in fe["functions"]}
    assert starts[0x800A6DD0].size == 8                # __osCleanupThread


@pytest.mark.grounded
def test_sbk1_grade_every_disagreement_explained(sbk1):
    g = sbk1[1]["grade"]
    s = g["functions"]
    for bucket in ("size_padding", "size_other", "missed_start", "extra_start",
                   "stale_whitelist"):
        assert s[bucket] == 0, (bucket, g["disagreements"].get(bucket))
    assert s["whitelisted"] == 2
    assert s["exact"] >= 2116                          # ratchet
    # Grader fires: statics recovered, reverse-order objects measured.
    assert s["start_only_uncheckable_size"] + s["uncheckable_static_start"] == 12
    assert g["reference_object_order"].get("reverse", 0) >= 1
    assert g["reference_unexplained_intervals"] == []


# ------------------------------------------------------------------ leaf after padding

LUI_T0 = 0x3C088000                # lui t0, 0x8000
LW_RA = 0x8FBF0014                 # lw ra, 0x14(sp)
POP = 0x27BD0018                   # addiu sp, sp, 0x18
B_BACK = 0x1000FFFF                # b . (infinite loop)


def test_leaf_after_padding_fires():
    # SBK2 setModelEntityVisibility / __moddi3 shape: no prologue, walks to jr ra.
    words = [ADDIU_V0, JR_RA, NOP, NOP, LUI_T0, JR_RA, NOP, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == {VRAM + 16}


def test_dead_epilogue_after_infinite_loop_is_not_a_function():
    # gameThreadMain: `b .; nop`, a nop, then the unreachable epilogue.
    words = [PROLOGUE, B_BACK, NOP, NOP, LW_RA, POP, JR_RA, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == set()


def test_leading_nop_function_starts_at_the_boundary():
    # libkmc __muldi3 begins with `nop`: zeros run past 0x10; start is 0x10.
    words = [ADDIU_V0, JR_RA, NOP, NOP, NOP, ADDU_V0, JR_RA, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == {VRAM + 16}


def test_branch_into_following_code_blocks_the_split():
    BEQZ_FWD = 0x10400005          # beqz v0, +5 -> index 6 (inside the "leaf")
    words = [BEQZ_FWD, NOP, JR_RA, NOP, LUI_T0, ADDIU_V0, JR_RA, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32, {VRAM}) == set()


SBK2 = os.path.expanduser("~/decomp/sbk2")
ROM2 = os.path.join(SBK2, "snowboardkids2.z64")


@pytest.mark.grounded
def test_sbk2_gcc_grade_every_disagreement_explained():
    if not os.path.exists(ROM2):
        pytest.skip("SBK2 ROM not present")
    from disasm import run
    fe = run.front_end(ROM2)
    g = run.receipt(fe, SBK2)["grade"]
    s = g["functions"]
    for bucket in ("size_padding", "size_other", "missed_start", "extra_start",
                   "stale_whitelist"):
        assert s[bucket] == 0, (bucket, g["disagreements"].get(bucket))
    assert s["exact"] >= 2261
    assert fe["extent"].rom(fe["extent"].text_end) == 0x851F0
    starts = {f.vram for f in fe["functions"]}
    assert {0x80000450, 0x80084220} <= starts     # leaf after padding; leading nop


def test_call_delay_slot_nop_is_not_padding():
    # SBK2 __umoddi3: `jal div64_64; nop` then code on a 16-byte boundary.
    words = [ADDIU_V0, ADDIU_V0, JAL, NOP, MOVE_A0_ZERO, JR_RA, NOP, NOP]
    assert functions.padding_boundaries(dec_of(words), VRAM, VRAM + 32) == set()


def _ri(cic, header_entry, main, bss):
    return rom.RomInfo(sha1="", byte_order="z64", size=0, title="", game_code="",
                       libultra_version="", cic=cic, header_entry=header_entry,
                       load_vram=header_entry, main_address=main, stack_top=None,
                       bss_start=bss, bss_size=None, traditional_entrypoint=True)


def test_unknown_cic_resolved_only_by_the_entry_jump():
    # 6103-style: header says 0x80100400, image actually loads at 0x80000400.
    ri = _ri("unknown", 0x80100400, 0x80000500, 0x80010000)
    assert rom.checked_load_vram(ri)[0] == 0x80000400


def test_known_cic_with_inconsistent_entry_refuses():
    with pytest.raises(ValueError):
        rom.checked_load_vram(_ri("6102", 0x80000400, 0x80300000, 0x80010000))


@pytest.mark.grounded
def test_sbk1_ledger_has_no_text_gaps(sbk1):
    led = sbk1[1]["ledger"]
    assert led["text_gap_bytes"] == 0 and led["overlapping_regions"] == 0
