"""Stage 6: per-function assembly and self-named symbols, from the front end.

Output goes to a directory of our own -- never into a reference repo:

    <out>/macro.inc                         glabel/endlabel/nonmatching macros
    <out>/<segment>/asm/<name>.s            one function, splat format
    <out>/symbol_addrs.txt                  name = vram; // type:func segment:..
    <out>/manifest.json                     every function: segment, vram, rom,
                                            size, padding, file

Names are generated, never borrowed: `func_<VRAM>` as spimdisasm prints them.
Overlays that share a load address keep the same spelling in different
segment directories; (segment, name) is the identity, as in splat.

The body is spimdisasm's text (it symbolises %hi/%lo pairs and branch
labels) cut to the function's size: the trailing alignment padding stage 3
split off is not part of the function and is not emitted inside it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

MACRO_INC = """# Generated by disasm.emit. Assembly macros for splat-format functions.
.macro glabel label, visibility=global
    .\\visibility \\label
    .type \\label, @function
    \\label:
        .ent \\label
.endm

.macro endlabel label
    .size \\label, . - \\label
    .end \\label
.endm

.macro alabel label, visibility=global
    .\\visibility \\label
    .type \\label, @function
    \\label:
        .aent \\label
.endm

.macro nonmatching label, size=1
.endm

.macro jlabel label, visibility=local
    \\label:
.endm

.macro dlabel label, visibility=global
    .\\visibility \\label
    \\label:
.endm

.macro enddlabel label
.endm
"""

PRELUDE = ('.include "macro.inc"\n.set noat\n.set noreorder\n.set gp=64\n\n'
           '.section .text\n\n')

# /* ROM VRAM WORD */ instruction comment spimdisasm prints on every line.
LINE_VRAM = re.compile(r"/\* [0-9A-F]+ ([0-9A-F]{8}) [0-9A-F]{8} \*/")


def function_text(sym, size: int) -> tuple[str, str]:
    """(name, text) for one spimdisasm function symbol, cut to `size` bytes."""
    text = sym.disassemble(migrate=False, useGlobalLabel=True)
    name = sym.getName()
    end = sym.vram + size
    keep = []
    for line in text.splitlines():
        if line.startswith("nonmatching "):
            continue
        m = LINE_VRAM.search(line)
        if m and int(m.group(1), 16) >= end:
            continue                       # alignment padding, not the function
        if line.strip().startswith("endlabel") or line.strip().startswith(".size"):
            continue
        keep.append(line)
    while keep and not keep[-1].strip():
        keep.pop()
    keep.append(f"endlabel {name}")
    return name, "\n".join(keep) + "\n"


def plain_register_names() -> None:
    """Numeric COP0/FCSR registers: GNU as rejects `mtc0 $t1, Compare` and
    `cfc1 $k1, $FpcCsr`, which handwritten libultra uses (splat projects
    paper over this with a header of #defines the pipeline does not have)."""
    import rabbitizer
    rabbitizer.config.regNames_vr4300Cop0NamedRegisters = False
    rabbitizer.config.regNames_userFpcCsr = False


def emit(fe: dict, out: Path) -> dict:
    plain_register_names()
    out = Path(out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "macro.inc").write_text(MACRO_INC, encoding="utf-8")
    segments = [("boot", fe["segment"], fe["functions"])] + [
        (o["segment"].name, o["segment"], o["functions"]) for o in fe["overlays"]]
    manifest, symbols = [], []
    for seg_name, seg, funcs in segments:
        sec = funcs.section
        size_of = {f.vram: f for f in funcs}
        d = out / seg_name / "asm"
        d.mkdir(parents=True, exist_ok=True)
        for sym in sec.symbolList:
            f = size_of[sym.vram]
            name, text = function_text(sym, f.size)
            rel = Path(seg_name) / "asm" / f"{name}.s"
            # gp=64: libultra's 64-bit `ld`/`dsrlv` must not expand to macros.
            (out / rel).write_text(PRELUDE + text, encoding="utf-8")
            rom_off = seg.rom_start + (f.vram - seg.vram)
            manifest.append({"segment": seg_name, "name": name, "vram": f"{f.vram:#010x}",
                             "rom": f"{rom_off:#x}", "size": f.size,
                             "padding": f.padding, "file": str(rel).replace("\\", "/")})
            symbols.append(f"{name} = 0x{f.vram:08X}; // type:func segment:{seg_name} "
                           f"rom:0x{rom_off:X} size:0x{f.size:X}")
    (out / "symbol_addrs.txt").write_text("\n".join(symbols) + "\n", encoding="utf-8")
    (out / "manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    return {"functions": len(manifest), "segments": len(segments), "out": str(out)}
