"""Stage 3: function boundaries inside CPU text.

spimdisasm does the splitting (handoff idea 1: do not write a disassembler).
Two things are ours:

* Seeds. Every function start stage 2 proved -- jal targets and address-taken
  pointers that walk as functions -- is registered in spimdisasm's context
  before analysis, so a function entered only by pointer (an exception
  handler, a thread entry) is split even when no `jal` names it.
* Padding. Zero words after a function's last control transfer and its delay
  slot are alignment padding, not part of the function: the compiler's
  `.size` excludes them and a reassembled function must too (bootThreadMain
  was one padding word away from exact). spimdisasm folds them into the
  preceding function; `split_padding` cuts them off and records them. The
  same padding also marks a boundary when nothing else does
  (`padding_boundaries`): osPfsIsPlug is never called, and only the zeros
  after __osCleanupThread's no-return jal say where it begins.
"""

from __future__ import annotations

from dataclasses import dataclass

import spimdisasm

from disasm.code_extent import CodeExtent, Decoder, _reg

# Control transfers after which a function may end. `jal` is here because a
# call that never returns (__osCleanupThread: jal osDestroyThread) is the
# last instruction of its function.
TRANSFER = {"jr", "j", "jal", "jalr", "b", "eret"}
NO_DELAY_SLOT = {"eret"}


@dataclass(frozen=True)
class Function:
    vram: int
    size: int            # bytes, excluding trailing padding
    padding: int         # trailing zero bytes cut off as alignment
    seeded: bool         # start was proven by stage 2 before splitting

    @property
    def end(self) -> int:
        return self.vram + self.size


def _body_end(dec: Decoder, start: int, end: int) -> int | None:
    """End of the last real instruction, counting a delay slot as real.

    Trailing zero words are padding only when the last non-zero word is a
    control transfer (its delay slot is kept even when it is a nop: `jr ra;
    nop`) or is that transfer's delay slot. Anything else returns None --
    a run of zeros after ordinary code is not known to be padding.
    """
    last = end - 4
    while last >= start and dec.word(last) == 0:
        last -= 4
    if last < start:
        return None
    op = dec.insn(last).getOpcodeName()
    if op in TRANSFER:
        return last + (4 if op in NO_DELAY_SLOT else 8)
    if last - 4 >= start and dec.insn(last - 4).getOpcodeName() in TRANSFER             and dec.insn(last - 4).getOpcodeName() not in NO_DELAY_SLOT:
        return last + 4
    return None


def split_padding(dec: Decoder, start: int, size: int) -> tuple[int, int]:
    """(size, padding): cut trailing zero words that follow the body's end."""
    end = start + size
    body = _body_end(dec, start, end)
    if body is None or body >= end:
        return size, 0
    return body - start, end - body


def padding_boundaries(dec: Decoder, lo: int, hi: int) -> set[int]:
    """Function starts implied by alignment padding (catalog: text-alignment-padding-is-not-function-body).

    A run of zero words that begins right after a control transfer's delay
    slot and ends on a 16-byte boundary, followed by a stack-frame prologue
    (`addiu sp, sp, -N`), is the gap between two objects' .text. The prologue
    guard is what keeps a load-delay `nop` inside a function from ever
    splitting it; a leaf function after padding is left to spimdisasm.
    """
    out = set()
    v = lo + 4
    while v < hi:
        if v % 16 or dec.word(v) == 0 or dec.word(v - 4) != 0:
            v += 4
            continue
        z = v - 4
        while z > lo and dec.word(z - 4) == 0:
            z -= 4
        d = dec.insn(v)
        prologue = (d.getOpcodeName() == "addiu" and _reg(d.rt) == "sp"
                    and _reg(d.rs) == "sp" and d.getProcessedImmediate() < 0)
        if prologue and z > lo and _body_end(dec, max(lo, z - 8), z) == z:
            out.add(v)
        v += 4
    return out


def find(rom: bytes, extent: CodeExtent, seeds: set[int] | None = None) -> list[Function]:
    seg = extent.segment
    text_rom_end = extent.rom(extent.text_end)
    ctx = spimdisasm.common.Context()
    ctx.changeGlobalSegmentRanges(seg.rom_start, seg.rom_end, seg.vram, seg.vram_end)
    dec = Decoder(rom, seg)
    if seeds is None:
        seeds = set(extent.functions) | padding_boundaries(
            dec, seg.vram, extent.text_end)
    for v in seeds:
        # isAutogenerated: binary-derived, exactly like spimdisasm's own jal
        # symbols. A plain addFunction() symbol is neither user-declared nor
        # autogenerated, so isTrustableFunction() is False for it -- and it
        # also displaces the trusted symbol spimdisasm would have made from
        # the jal. Seeding 0x80000450 that way deleted initControllerSubsystem.
        ctx.globalSegment.addFunction(v, isAutogenerated=True,
                                      vromAddress=extent.rom(v))
    sec = spimdisasm.mips.sections.SectionText(
        ctx, seg.rom_start, text_rom_end, seg.vram, seg.name, rom,
        seg.rom_start, None)
    sec.analyze()

    out = []
    for sym in sec.symbolList:
        size, pad = split_padding(dec, sym.vram, sym.sizew * 4)
        out.append(Function(sym.vram, size, pad, sym.vram in seeds))
    return out
