"""Store-order hypotheses for a pure instruction-order residual.

Generated byte-view lvalues are outside the ordinary statement-order parser.
These swaps are compiler candidates, not claims of C alias independence: the
target object certificate must decide, including when a RHS reads another base.
"""
from collections import Counter, defaultdict
import re

from solver import c89, diffrepair


STORE = re.compile(
    r'(?m)^[ \t]*\(\*\((?:s32|u32)\s*\*\)\(\(unsigned char\s*\*\)(?P<base>\w+)'
    r'\s*\+\s*(?P<offset>0[xX][0-9A-Fa-f]+|[0-9]+)\)\)\s*=\s*(?P<rhs>[^;\n]+);')
WORD_STORE = re.compile(r'^sw\s+\$?\w+,\s*(0x[0-9a-f]+|[0-9]+)\(\$?(\w+)\)$')


def propose(code: str, diff: str, *, limit: int = 8):
    """Swap adjacent disjoint word stores witnessed in a reordered diff hunk."""
    from solver.rewrites import Rewrite
    target, candidate = diffrepair._streams(diff)
    masked = c89._mask(code)
    if (limit <= 0 or not target or target == candidate or Counter(target) != Counter(candidate)
            or re.search(r'\bvolatile\b', masked)):
        return []
    offsets = defaultdict(set)
    for instruction in target:
        match = WORD_STORE.fullmatch(instruction)
        if match and match[2] not in ('sp', 'gp'):
            offsets[match[2]].add(int(match[1], 0))
    stores = list(STORE.finditer(masked))
    output = []
    for left, right in zip(stores, stores[1:]):
        if masked[left.end():right.start()].strip() or left['base'] != right['base']:
            continue
        # A preceding control header/label can make only the first store
        # conditional. Require an ordinary statement/block boundary.
        prefix = masked[:left.start()].rstrip()
        if not prefix or prefix[-1] not in ';{}':
            continue
        a, b = int(left['offset'], 0), int(right['offset'], 0)
        if a % 4 or b % 4 or a == b or not any({a, b} <= witnessed for witnessed in offsets.values()):
            continue
        lhs, rhs = left['rhs'].strip(), right['rhs'].strip()
        # Restrict to a zero-fill next to a computed word. Calls, updates and
        # embedded assignments need their own control/dataflow analysis.
        if (lhs == '0') == (rhs == '0'):
            continue
        # Remove only known scalar casts before detecting an indirect call;
        # otherwise `(s32) (expression)` would look like `(*fn)()`.
        checked = [re.sub(r'\(\s*(?:s32|u32|int|unsigned int|long|unsigned long)\s*\)', '', text)
                   for text in (lhs, rhs)]
        if any(re.search(r'\b\w+\s*\(|[)\]]\s*\(|\+\+|--|<<=|>>=|(?<![=!<>])=(?!=)|[,{}]', text)
               for text in checked):
            continue
        changed = (code[:left.start()] + code[right.start():right.end()]
                   + code[left.end():right.start()] + code[left.start():left.end()] + code[right.end():])
        output.append(Rewrite(f'byte-view store order {left["base"]} 0x{a:X}/0x{b:X}',
            'byte-view-order', lambda source, old=code, new=changed: new if source == old else source))
        if len(output) >= limit:
            break
    return output
